---
engines:
  fixme:
    enabled: true
    exclude_fingerprints:
    - b3d64fc578bcf5ae4e0dbff33f60dc4e
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  markdownlint:
    enabled: true
ratings:
  paths:
  - "test/**"
exclude_paths:
- node_modules/
- .codeclimate.yml
